### ISSUE TITLE
使用日志门面代替控制台打印

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#12]
e.printStackTrace() 只能输出到控制台，没法通过日志门面向各个日志框架写到日志文件中。我感觉 lombok 可以不引入，slf4j 的的引入并不会造成太大的影响，而且 slf4j 属于日志门面，适配各个日志框架，灵活性要更高一些，引入之后也不会对项目造成影响。而且，一般做项目大多数都是搭配日志框架输出的，很少直接用控制台输出的，这样定位问题也不方便。

**Comment by MisterChangRay** [comment]
> e.printStackTrace() 只能输出到控制台，没法通过日志门面向各个日志框架写到日志文件中。我感觉 lombok 可以不引入，slf4j 的的引入并不会造成太大的影响，而且 slf4j 属于日志门面，适配各个日志框架，灵活性要更高一些，引入之后也不会对项目造成影响。而且，一般做项目大多数都是搭配日志框架输出的，很少直接用控制台输出的，这样定位问题也不方便。

多谢老哥，之前直接输出的在V2.2.1中直接抛出了。
然后很多异常属于解析阶段异常，只能在调试阶段抛出。
可以在下个版本中引入slf4j，确实可以通过日志做一些警告提示。
