### ISSUE TITLE
提个建议，去掉order数据，按结构体中的属性顺序排序

### ISSUE THREAD

**Issue by hurui79** [MisterChangRay/magic-byte#13]
有个上百个字段的结构体，一个个写order有点费劲

**Comment by MisterChangRay** [comment]
> 有个上百个字段的结构体，一个个写order有点费劲

1. 显示声明可以避免随意字段顺序调整而造成的异常问题，通常显示申明更容易发现
2. 最重要的一点，java 反射获取的字段是不保证顺序的，这一点在jdk文档中有说明。具体参阅：
   - https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getFields--
    - https://stackoverflow.com/questions/5001172/java-reflection-getting-fields-and-methods-in-declaration-order

**Comment by MisterChangRay** [comment]
> 有个上百个字段的结构体，一个个写order有点费劲

还有一点，一个结构体上百个字段是不是有点不合理。可以组合嵌套的，看起来似乎需要拆分一下。

**Comment by hurui79** [comment]
> > 有个上百个字段的结构体，一个个写order有点费劲
> 
> 1. 显示声明可以避免随意字段顺序调整而造成的异常问题，通常显示申明更容易发现
> 2. 最重要的一点，java 反射获取的字段是不保证顺序的，这一点在jdk文档中有说明。具体参阅：
>    
>    * https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getFields--
>    * https://stackoverflow.com/questions/5001172/java-reflection-getting-fields-and-methods-in-declaration-order

明白了。原来还有这种问题啊。
那javolution 是怎么解决排序问题的，他的用法好像就不需要order排序属性，不过他的自定义类型用着很恶心。

**Comment by hurui79** [comment]
> > 有个上百个字段的结构体，一个个写order有点费劲
> 
> 还有一点，一个结构体上百个字段是不是有点不合理。可以组合嵌套的，看起来似乎需要拆分一下。

这个可不由我决定，edgetech的jsf官方文档就是这样，他的头信息比较多没法嵌套。

**Comment by MisterChangRay** [comment]
> > > 有个上百个字段的结构体，一个个写order有点费劲
> > 
> > 
> > 还有一点，一个结构体上百个字段是不是有点不合理。可以组合嵌套的，看起来似乎需要拆分一下。
> 
> 这个可不由我决定，edgetech的jsf官方文档就是这样，他的头信息比较多没法嵌套。

嗯嗯，处理出来就好
