### ISSUE TITLE
如果是动态的有办法呢？

### ISSUE THREAD

**Issue by taolive** [MisterChangRay/magic-byte#14]
如：
当第0个字节是 0x01的时候，则第1 ~ 4个字节 需要解析为：对象中的姓名
当第0个字节是0x02的时候，则第1 ~ 3个字节需要解析为：对象中的地址

**Comment by MisterChangRay** [comment]
按照你的内容，第一个字节为报文类型，第二个字节为文本型，可以统一设置为最大值比如20个字节。
然后数据传输就行了啊，业务方面根据第一个字节来进行业务处理。

如果觉得统一设置为最大值浪费空间，可以考虑使用dynamicSizeOf属性。

即第一个字节为报文类型，第二个字节为文本长度， 第三个字段为文本型-这个字段为真实的文本信息字段，长度使用第二个字节的值。

**Comment by MisterChangRay** [comment]
数据传输层应该和业务层分开，我看你这里既参杂了业务的概念，又有传输的概念。

建议还是分开处理。传输层只需要按要求进行数据传输即可。业务层才是通过字节来区分是姓名还是邮箱。
