### ISSUE TITLE
提个建议，MagicField 属性的converter参数可以接受你的ConverterUtil方法

### ISSUE THREAD

**Issue by hurui79** [MisterChangRay/magic-byte#15]
应用场景 就是 我的其中一个字段需要用 ushort去接。但是java中又没有ushort，ConverterUtil.byteToNumber(byte[])，你有提供了类似的工具类。那么结合起来岂不是很爽。如果能像我说的 那样直接转换的话，会方便许多。
![image](https://user-images.githubusercontent.com/16483840/231936833-c32d0190-e1ab-4788-ac3e-6760fc6bf9d2.png)
例如这么写。直接在属性那块就把heading的值矫正过来了。

**Comment by hurui79** [comment]
我想明白了，java应该不行

**Comment by MisterChangRay** [comment]
这个是实现不了的，因为如图`Heading`数据类型本来就是short, 
我转换为无符号数后可能会超过short的最大值
也就是转换后的值只能存在int/long之类的数据类型中，如果存short将会导致数据失真

**Comment by FULaBUla** [comment]
> 我想明白了，java应该不行

这个应该也可以，我看 mapStruct 就可以在注解里写表达式，然后就能通过表达式快速赋值
