### ISSUE TITLE
dynamicSize & dynamicSizeOf only use one in the class

### ISSUE THREAD

**Issue by xuelang2009** [MisterChangRay/magic-byte#16]
class A {
 /**
     * size 必须设置，为了保险起见，默认给了100个数量，应该够了...
     * 没有长度标识，只能动态计算，剩下的就是它
     */ 
    @MagicField(order = 4,  size = 100, dynamicSize = true)  //动态长度，从数据中获取...
    protected List《B》 list;  
}
class B{
    /**
     * 值长度，将值转化为byte[]后的值长度...即：value.size()
     */
    @MagicField(order = 2)
    private int len;

    /**
     * 真实数据
     * 需要自行将数据格式转为byte..
     */
    @MagicField(order = 3, dynamicSizeOf = 2)
    private ArrayList<Byte> value;
}
这种情况下，只能将B改为Byte，然后每次都得分为多次进行编解码吗？或者写很多自定义序列化器？
因为 Class B 有很多种定义 。

**Comment by MisterChangRay** [comment]
是的啊，因为每个数据实体解析规则不一样的啊。
你可以直接定义一个变长的byte[]，解析完成后再解析这个数组

**Comment by MisterChangRay** [comment]
你好，我完善了文档，增加了更多的示例；可以参考一下：
https://github.com/MisterChangRay/magic-byte/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BA%8F%E5%88%97%E5%8C%96%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#13--%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BA%8F%E5%88%97%E5%8C%96%E6%9C%AA%E7%9F%A5%E7%B1%BB%E5%9E%8B
