### ISSUE TITLE
自定义序列化器 对于 属性List<> 不会触发

### ISSUE THREAD

**Issue by xuelang2009** [MisterChangRay/magic-byte#17]
@MagicClass
public class Staff4 {
    @MagicField(order = 1)
    private int id;
    @MagicField(order = 2, calcLength = true)
    private int length;
    @MagicConverter(converter = CustomBook3Converter.class, attachParams = "1")
    @MagicField(order = 5, size = 2)
    private List<Book3> book;  // 序列化器 不会触发
    @MagicConverter(converter = CustomBook3Converter.class, attachParams = "2")
    @MagicField(order = 7, size = 2)
    private List<Book3> book2; // 如果定义改为 private Book3  book2; 则序列化器会触发。
    @MagicField(order = 14, size = 4)
    private String name;

**Comment by MisterChangRay** [comment]
// 序列化器 不会触发
private List book;
这里list没有类型，也是size=0；也就不会触发了

**Comment by MisterChangRay** [comment]
也就是, 声明应该为 List<Type>, 而且这个type需要是一个`@MagicClass`类
你也可以直接申明一个Type, 然后进行序列化。

**Comment by xuelang2009** [comment]
List<Book3> 有类型的，List《Book3》有类型的，不知道为啥，我弄过来以后，尖括号就没有了。 就是你的测试程序 Staff4

**Comment by MisterChangRay** [comment]
好的，我检查一下

**Comment by MisterChangRay** [comment]
已经修复于V2.3.3
