### ISSUE TITLE
针对 dynamicSize & dynamicSizeOf 不能在一个类中同时存在，做的修订，不确定是否存在隐藏问题

### ISSUE THREAD

**Issue by xuelang2009** [MisterChangRay/magic-byte#19]
在 CollectionReader.java 文件，readFormBuffer 方法中，

if(TypeEnum.LIST == this.fieldMetaInfo.getType()) {
            long allocSize = count * fieldMetaInfo.getGenericsField().getElementBytes();
            ExceptionUtil.throwIFOOM(allocSize, fieldMetaInfo.getGenericsField().getFullName());

            //FIXME : 取消了count
            //List<Object> list = new ArrayList<>(count);
            List<Object> list = new ArrayList<>();

            for(int i=0; i<count; i++) {

                //FIXME 添加了if判断，尝试解决如下问题：
                //FIXME 针对List<T> dySize = true,  并且T中含有dySizeOf的问题
                //FIXME 针对 类下同时存在  ArrayList<Byte> dySizeOf 和  List<T> dySize = true， order=最后  的问题
                //TODO 需要构建大量的测试类...
                //TODO 需要测试 Size 过大 或者 过小问题
                //目前简单测试无问题
                //<1> 注释掉dySize 和 dySizeOf同时存在的检测
                //<2>
                //T中包含dySizeOf且没有计算，导致T.length长度偏小
                //suffixBytes 好像永远是0 或者小于0？，故导致fillBytes偏大或者正常
                //故fillBytes/T.length 计算出来的count偏大，但是buffer的读取有效数据是不变的
                //故根据buffer是否存在有效数据，跳出循环； 否则在List中会返回很多空T
                if(buffer.capacity() - buffer.position() <= 0) break;

                list.add( fieldMetaInfo.getGenericsField().getReader().readFormBuffer(buffer, entity));
            }

            return list;
        }
经过简单测试，序列化和反序列化 没有问题。因为没有全部翻阅内部处理流程， 就得作者从代码流程处理的角度考虑了。

**Comment by MisterChangRay** [comment]
希望可以增加完善的测试用例测试用例
以及需要注意框架支持无限嵌套，也就是需要检查父子级
完善后提个PR

**Comment by MisterChangRay** [comment]
对了，框架时可以实现局部解析的，一般来说你可以先解析出报文类型。再根据报文类型来解析到具体的结构体
