### ISSUE TITLE
ClassParser

### ISSUE THREAD

**Issue by wuyongdec** [MisterChangRay/magic-byte#2]
Hello Ray,

I have some doubt about the line  94 of the ClassParser
`                dynamicRef.setDynamicRef(fieldMetaInfo);
`
why do you set the dynamicRef to the fieldMetaInfo ?

**Comment by MisterChangRay** [comment]
动态字段实际上操作的也是普通的字段， 只是因为泛型而导致类型不太容易确定， 确定后可以直接赋予具体的操作字段。方便解析的效率。
