### ISSUE TITLE
支持“yyyy-MM-dd HH:mm:ss” 等格式的时间转换

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#23]
由于协议比较老，部分地方使用的还是 yyyy-MM-dd HH:mm:ss 格式的字符串传的时间信息，而不是使用的秒数，所以希望可以以字符串的形式支持这种格式的时间和二进制之间的转换。也可以将这种转换提供为默认的实现了 MConverter 接口的自定义转换类的方式提供支持

**Comment by MisterChangRay** [comment]
> 由于协议比较老，部分地方使用的还是 yyyy-MM-dd HH:mm:ss 格式的字符串传的时间信息，而不是使用的秒数，所以希望可以以字符串的形式支持这种格式的时间和二进制之间的转换。也可以将这种转换提供为默认的实现了 MConverter 接口的自定义转换类的方式提供支持

自定义解析器可以实现，下个版本计划新增内置
