### ISSUE TITLE
对不同版本协议的支持

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#24]
1. 可能项目需要兼容多个版本的协议，不同版本间的字段不相同，但是目前的状态一个类无法根据版本选择性的对类中的一部分属性进行序列化，希望可以增加
2. 除此之外某些版本不支持的属性也希望可以配置默认值在反序列化之后自动就有值了

**Comment by MisterChangRay** [comment]
> 

多个版本只能定义不同的结构体，代码中来根据不同的版本号来进项单独的序列化

**Comment by MisterChangRay** [comment]
因为私有协议自由度高，工具对其进项数据版本兼容就需要提供公共模板进行支持。
这种方式与私有协议又背道而驰了，所以这一块还是交给协议解析本身来做比较好。
这个工具本身的意义在于序列化本身。哈哈
