### ISSUE TITLE
能否对整个 list 设置自定义序列化

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#26]
目前的自定义序列化是对 list 遍历，然后对 list 里每一个 item 单独做序列化处理的，但是我希望可以对整个 list 做序列化，也就是直接把 list 给我，我来对 list 做整体的处理

**Comment by MisterChangRay** [comment]
> 目前的自定义序列化是对 list 遍历，然后对 list 里每一个 item 单独做序列化处理的，但是我希望可以对整个 list 做序列化，也就是直接把 list 给我，我来对 list 做整体的处理

对于list来说，整个给和单个处理有什么区别吗

**Comment by FULaBUla** [comment]
就是有时候有的字段不属于 List 中的 Object 中，想在序列化的时候手动增加到二进制中，所以相对整个 list 做处理

**Comment by MisterChangRay** [comment]
> 就是有时候有的字段不属于 List 中的 Object 中，想在序列化的时候手动增加到二进制中，所以相对整个 list 做处理

不太明白你的意思呢，不过即使是单个循环你也可以这么做，当遇到你不想序列化的对象时，返回空字节数据，这不就等于没序列化出去。
因为序列化本身流程还是converter控制，你可以返回结果控制忽略或者序列化某些对象。
