### ISSUE TITLE
     如何支持二维的数组呢  ，就是吧这样的二维的数据 怎么放入

### ISSUE THREAD

**Issue by jasonccs** [MisterChangRay/magic-byte#29]
如何支持二维的数组呢  ，就是吧这样的二维的数据 怎么放入

@MagicField(order = 15, size = 4)
private List<List<UserInfo>> param = List.of(  
    List.of(new UserInfo(), new UserInfo()),  
    List.of(new UserInfo(), new UserInfo()),  
    List.of(new UserInfo(), new UserInfo()),  
    List.of(new UserInfo(), new UserInfo())  
);

   @MagicClass(byteOrder = ByteOrder.LITTLE_ENDIAN)
    @Data
    public static class UserInfo {

        @MagicField(order = 7)
        private short name;

        @MagicField(order = 9)
        private byte age;

    }
    
     如何支持二维的数组呢  ，就是吧这样的二维的数据 怎么放入

     [
      [{"name":"t","age":1},{"name":"t","age":1}],
      [{"name":"t","age":1},{"name":"t","age":1}],
      [{"name":"t","age":1},{"name":"t","age":1}]
]

**Comment by MisterChangRay** [comment]
框架暂不支持二维数组的

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。
