### ISSUE TITLE
含有中文无法正常展示，咋办

### ISSUE THREAD

**Issue by jasonccs** [MisterChangRay/magic-byte#3]
@MagicField(order = 6,size = 64)
    private String devic
含有中文无法正常展示，咋办

**Comment by MisterChangRay** [comment]
一般来说不推荐使用中文，如果一定要使用的话
有个charset 配置属性；可以指定字符集编码为UTF8或其他中文字符集，
注意字符串长度

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。
