### ISSUE TITLE
无法计算接口类的长度

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#35]
如果 @MagicField 注解的属性类型是接口类则计算的长度为 0，因为在计算长度的时候是通过类的属性计算的，而不是通过实际类型动态计算的

**Comment by MisterChangRay** [comment]
在运行时，只有接口信息，java有泛型擦除，没有实际数据实体定义。
无法解析到具体类型进行运算的

**Comment by FULaBUla** [comment]
ClassManager.getClassMetaInfo(object.getClass()); 的这个地方其实可以传 Object，然后 
```java 
for (Field field: object.getClass().getDeclaredFields()) {
    field.setAccessible(true);
    field.get(object).getClass();
}
```
就可以取到实际的类型了

**Comment by MisterChangRay** [comment]
我们是先通过定义数据结构再进行解析这样效率较高。
如果运行时解析的话，兄弟可以基于这个修改一套

**Comment by FULaBUla** [comment]
突然想到，dynamicSize 是运行时解析的长度，是不是这里拓展一下就可以拿到了
