### ISSUE TITLE
MConverter 的 pack 接口希望能把已经解析的属性信息作为入参传入

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#36]
在实现自定义解析的时候有时候会需要已经解析的数据辅助进行判断然后决定如何做二进制转对象，不想在 pack 里再重新解析一下之前已经解析过的数据，这样效率太低了。如果能把已解析完的属性给进来就太好了

**Comment by MisterChangRay** [comment]
不会全部遍历解析的。

当指定结构遍历后, 剩余字节数将不会访问。

比如先解析`head`， 就只会解析head里定义的字节数.

你的意思是解析message时，包含有head, 此时效率会很慢？

一般head本身字节数很少, 可以忽略不计

**Comment by FULaBUla** [comment]
您可以看一下 https://github.com/MisterChangRay/magic-byte/pull/37 里我在 Protocol 类里写的自定义解析方法，我要拿到头里的数据就要重新解一下头太麻烦了，如果能把已解析的属性给我就可以直接用了

**Comment by MisterChangRay** [comment]
> 您可以看一下 #37 里我在 Protocol 类里写的自定义解析方法，我要拿到头里的数据就要重新解一下头太麻烦了，如果能把已解析的属性给我就可以直接用了

你的意思是将解析中的对象作为参数传入吗？

**Comment by FULaBUla** [comment]
> > 您可以看一下 #37 里我在 Protocol 类里写的自定义解析方法，我要拿到头里的数据就要重新解一下头太麻烦了，如果能把已解析的属性给我就可以直接用了
> 
> 你的意思是将解析中的对象作为参数传入吗？

是的

**Comment by FULaBUla** [comment]
是不是 unpack 把之前已经转成二进制的数据或者要序列化的对象传过来，对于序列化也有用 #42

**Comment by MisterChangRay** [comment]
unpack对象有传的 ,pack对象传参已经新增
