### ISSUE TITLE
ClassManager 的 cache 在启动的时候扫描，在使用的时候效率更高

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#4]
如果在启动的时候像 spring 一样注解扫描，性能会比第一次使用的时候高，同时避免 cache 是 hashmap 的多线程问题

**Comment by MisterChangRay** [comment]
> 如果在启动的时候像 spring 一样注解扫描，性能会比第一次使用的时候高，同时避免 cache 是 hashmap 的多线程问题

这个是提供工具类的支持程度，没必要进行全局扫描。
实际应用中可以做一个单实例工具类来进行扩展使用

**Comment by MisterChangRay** [comment]
> > 如果在启动的时候像 spring 一样注解扫描，性能会比第一次使用的时候高，同时避免 cache 是 hashmap 的多线程问题
> 
> 这个是提供工具类的支持程度，没必要进行全局扫描。 实际应用中可以做一个单实例工具类来进行扩展使用

增加magic-byte-spring-boot-starter

已添加到V2.2.0
