### ISSUE TITLE
MConverter 的 unpack 接口希望能把要序列化的对象信息作为入参传入

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#42]
存在使用对象的属性信息联合判断进行自定义序列化，或者需要已经序列化成二进制的数据做其他操作

**Comment by MisterChangRay** [comment]
pack时传入可以获取到参数，unpack传入序列化的字节没有什么做用啊。而且呗操作后还容易影响自身序列化流程。

**Comment by MisterChangRay** [comment]
pack时传入可以获取到参数，unpack传入序列化的字节没有什么做用啊。而且呗操作后还容易影响自身序列化流程。

**Comment by FULaBUla** [comment]
> pack时传入可以获取到参数，unpack传入序列化的字节没有什么做用啊。而且呗操作后还容易影响自身序列化流程。

如果能实现对校验字段以外的数据自定义计算校验值并返回 byte[] 这个需求就没用了
