### ISSUE TITLE
希望可以自定义实现校验和且支持 byte[] 类型作为校验和数据类型

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#43]
对于校验和和检查校验和的实现希望可以自定义且支持返回 byte[]，因为我希望对除了校验和属性之外属性已经序列化的二进制数据计算校验和，比如按 sha256 计算，那返回的值类型就一定是 byte[] 不能是非数组类型

**Comment by MisterChangRay** [comment]
一般网络序会考虑节约资源，hash一般选择crc16,crc32之类的。

**Comment by MisterChangRay** [comment]
不过可以加上

**Comment by MisterChangRay** [comment]
你可以看作数值类，也可以看作最大8字节. 是足够的了

**Comment by FULaBUla** [comment]
不行啊，我们不用crc32，用的别的，不传 byte[] 发不过去，或者发过去，那边不认。接收端是 c 的程序

**Comment by MisterChangRay** [comment]
嗯 已经加到版本支持了

**Comment by FULaBUla** [comment]
> 嗯 已经加到版本支持了

感谢
