### ISSUE TITLE
dynamicSizof wiki 没更新

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#45]
dynamicSizof wiki 没更新，新的 dynamicSizof 的改动是破坏性的，旧代码都要进行修改 >_<

**Comment by MisterChangRay** [comment]
新老版本不兼容很正常的 ，再说，这个改动也不算大。哈哈

**Comment by FULaBUla** [comment]
> 新老版本不兼容很正常的 ，再说，这个改动也不算大。哈哈

唉，我得把所有写了order值的改成属性名字
