### ISSUE TITLE
  @MagicConverter 的 attachParams 能否通过读取别的值获取参数

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#49]
直接在注解定义有些死板，是否可以考虑从其他属性读取这个参数值，传入实现的接口便于动态反序列化

**Comment by MisterChangRay** [comment]
这个可以支持下

**Comment by MisterChangRay** [comment]
现在已经吧序列化中的对象当参数传入了，你这个从对象里也可以直接获取得到啊

**Comment by FULaBUla** [comment]
> 现在已经吧序列化中的对象当参数传入了，你这个从对象里也可以直接获取得到啊

是可以直接得到，但是再想如果直接能从 attachParams 动态取到就可以少了 Object 类型转换，然后再从里面 get 值的几步操作了，后续可以进阶给 attachParams 这个增强实现配置一个类型注册，就可以吧 customConvert 省了，这样越来越简单了。否则感觉 attachParams 存在的意义就不大了。而且这么提供一种方式可以让框架更灵活

**Comment by MisterChangRay** [comment]
attachParams  从对象获取的话，也是需要解析后才去拿值。和你直接从参数中拿一样的啊。

如果从偏移量拿的话，那自己也可以从字节数据里面自己定位拿。

**Comment by MisterChangRay** [comment]
你的消息类型不会设计在IP后面了吧 哈哈

**Comment by FULaBUla** [comment]
> 你的消息类型不会设计在IP后面了吧 哈哈

协议是别的同事设计的，用的就很头疼唉

**Comment by FULaBUla** [comment]
> attachParams 从对象获取的话，也是需要解析后才去拿值。和你直接从参数中拿一样的啊。
> 
> 如果从偏移量拿的话，那自己也可以从字节数据里面自己定位拿。

是这样的， 就是想省略一步类型转换再 get 的情况。而且目前传入的 Object 没法像改造后的 dynamicSizeof 从包含他的类的别的属性拿值，因为 Object 的类型仅是这个调用 customConvert 的属性的类型

**Comment by MisterChangRay** [comment]
嗯，传入的Object，应该传入根基对象
