### ISSUE TITLE
默认字符编码能否为 uft-8 或者提供全局一键配置的配置类

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#5]
由于要传输中文，整个系统默认 utf-8 编码，一个个设置太麻烦了，还容易写错，不便于维护，需要将默认值改为 utf-8 或者像 spring 一样在配置文件中配置默认值，这样统一维护

**Comment by FULaBUla** [comment]
或者在调用 unpack 和 pack 的时候设置编码

**Comment by MisterChangRay** [comment]
> 或者在调用 unpack 和 pack 的时候设置编码

有道理， 可以加到下一个版本
