### ISSUE TITLE
自定义序列化传入的Object，应该传入根基对象

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#51]
自定义序列化里的 pack 和 unpack 方法有时候需要配合根基对象里的其他属性的值做序列化和反序列化

**Comment by FULaBUla** [comment]
哥，请问下个版本什么时候出？我现在开发被这个问题卡主了

**Comment by MisterChangRay** [comment]
这周吧

**Comment by FULaBUla** [comment]
> 这周吧

突然感觉这样也有问题，就是如果一个类被复用了，那么传入的根基对象就不好判断，要做多个 instanceof，是不是可以同时给两个，一个是自己，一个是根基，这样可以根据需要做不同的操作啥的

**Comment by MisterChangRay** [comment]
只能传入父对象和根基对象，自己不是自定义解析过程吗

**Comment by FULaBUla** [comment]
> 只能传入父对象和根基对象，自己不是自定义解析过程吗

是的，有的时候需要根基，有的时候用这个类作为属性所在的类会更快更方便
