### ISSUE TITLE
异常栈无法看出报错位置

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#53]
目前的异常栈在报错的时候只会打印一个报错信息，如果是配置序列化没配对的情况则无法看到具体序列化或者反序列化到哪个类的哪个属性的时候出现的问题

**Comment by MisterChangRay** [comment]
具体一点呢

**Comment by MisterChangRay** [comment]
大多数异常都添加了位置信息，所以需要具体信息添加

**Comment by FULaBUla** [comment]
嗯嗯，在公司内网里测出来的，那个异常信息搞不出来，我明天看看，简化一个测试用例。大概的意思就是我可能是自定义序列化的时候出现空指针异常的了，然后只能看到异常栈打印咱们的框架里显示出空指针异常，但是看不出是在序列化或者反序列化哪个属性的时候报的错。还有别的没记住，明天再看看
