### ISSUE TITLE
byte[] 这种不定长类型如果配置了 custom 注解还检查是否指定长度

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#55]
应该有 custom 注解定义自定义长度解析之后就不检查有没有在注解里指定定长或者基于哪个属性的值确定长度了

**Comment by MisterChangRay** [comment]
无论是list还是array，自定义序列化也需要指定长度的。 
目前集合类数据自定义序列化是分别调用成员数这么多次来实现的；也就是说用户只能控制对象的序列化过程。
这是设计如此

如果你不需要，可以直接用对象封装一层
