### ISSUE TITLE
BUG：作为属性的类的属性如果都使用了 @MagicConverter 将会导致反序列结果不正确

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#57]
测试代码参考合并请求 #56 

```java
@MagicClass
public class CustomClassA {

    @MagicField(order = 1)
    private int number;

    @MagicField(order = 2)
    private B b;

    @MagicClass
    public static class B {

        @MagicField(order = 1)
        @MagicConverter(converter = TypeEnumConverter.class)
        private TypeEnum typeEnum;
    }

    public enum TypeEnum {
        A, B
    }
```

目前通过调试追踪代码看到，在这种使用情况下，生成的属性 b 的 elementbytes 的值为 0，导致反序列化的时候跳过了对应属性的反序列化，导致反序列化结果里 b 的值为 null

**Comment by FULaBUla** [comment]
哥，这个问题啥时候能修复？我感觉是不是判断的 elementbytes 初始值为负数，后面判断是否大于等于 0 就能解决？

**Comment by MisterChangRay** [comment]
不好意思老哥，最近公司比较忙，这个晚一点修复

**Comment by MisterChangRay** [comment]
已经修复了，

不过你这里既然要自定义序列化，为啥不直接将注解打到list上？而要将list再包一层

**Comment by FULaBUla** [comment]
测试是一个简化的模型，我的这里有多态还有多个属性，没法放外面。而且，我记得没法对 list 做自定义序列化，之前讨论过 https://github.com/MisterChangRay/magic-byte/issues/26
@MisterChangRay

> 已经修复了，
> 
> 不过你这里既然要自定义序列化，为啥不直接将注解打到list上？而要将list再包一层

**Comment by MisterChangRay** [comment]
增加了 handleCollection 配置，可以自定义序列化整个集合。
