### ISSUE TITLE
功能增强：反序列化方法可以传入一个 customConvert 变量

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#62]
如果我想只对一个接口类做反序列化，这个接口类有多个实现类，反序列化成哪个实现类通过编写 custom Convert 做处理，那么就没法直接调用 `MagicByte.pack(data, ClassA.class);` 做反序列化，如果这个时候能传入一个 custom convert 进去的话就可以了

序列化也可以加一个

**Comment by FULaBUla** [comment]
序列化也可以加一个

**Comment by MisterChangRay** [comment]
这个感觉和使用消息注册方式解析报文思路是一样的
实现类实现`MagicMessage `, 标识并注册`type`字段，就可以根据类型解析出特定实例的

**Comment by FULaBUla** [comment]
感觉场景不太一致，我这边主要是直接用一个接口类做二进制数据的反序列化，没法注册 type，因为回合别的冲突
