### ISSUE TITLE
希望增加时间类的序列化支持

### ISSUE THREAD

**Issue by FULaBUla** [MisterChangRay/magic-byte#7]
增加对时间类：Date、Instant、LocalDate、LocalTime、LocalDateTime等的支持，默认按照 yyyy-MM-dd HH:mm:ss 格式及长度转换数据，或者根据指定的时间格式转换对应的值，也可以自己设定长度。同时除了这种方式还可以指定按照 int 或者 long 直接将时间转为秒或者毫秒的方式转换

**Comment by MisterChangRay** [comment]
已添加到V2.2.0

**Comment by MisterChangRay** [comment]
> 

时间日期这种数据传输时建议使用long或者int数据类型。
一般来说，项目中的业务层实体，和传输层的实体类是分开定义的。这样可以自己进行转换
